version: '3.8'

services:
  # Redis for Socket.IO adapter and caching
  redis:
    image: redis:7-alpine
    container_name: voxora-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: dev123
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes --requirepass dev123
    networks:
      - voxora-dev-network

  # MongoDB for data persistence
  mongodb:
    image: mongo:7
    container_name: voxora-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev123
      MONGO_INITDB_DATABASE: voxora-chat-dev
    volumes:
      - mongodb_data_dev:/data/db
      - ../apps/api/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - voxora-dev-network

  # MongoDB Express for database management (optional)
  mongo-express:
    image: mongo-express:1.0.2-18
    container_name: voxora-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123
      ME_CONFIG_MONGODB_URL: mongodb://admin:dev123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: dev123
    depends_on:
      - mongodb
    networks:
      - voxora-dev-network

volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  voxora-dev-network:
    driver: bridge
